logging:
  path: E:/logs
spring:
  mvc:
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: false
  resources:
    #不要为我们工程中的资源文件建立映射
    add-mappings: false
#  datasource:
#    hikari:
#      jdbc-url: ""

