logging:
  path: E:/logs
spring:
  mvc:
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: false
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: admin
    filter:
      dispatcher-types:

